---
Title   : "Quantmod"
Author  : "cms"
Date    : "February 11, 2019"
Output  : html_document
---

```{r}
setwd("\Users\Administrator\Desktop\Quantmod II")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(quantmod)
library(PerformanceAnalytics)
library(RColorBrewer)
library(tseries)
library(lubridate)
library(Quandl)
Quandl.api_key("zrcB2Ejv9UmvhPCUsy2_")
options("getSymbols.yahoo.warning"=FALSE)
```

# Review of the Last Project (i.e., Ad, Cl, getsymbols, ect.)

```{r}
msft <- getSymbols("MSFT", auto.assign = F)
head(msft)
tsla <- getSymbols("TSLA", auto.assign = F)

tsla_daily_return <- dailyReturn(tsla$TSLA.Adjusted)
head(tsla_daily_return)
```

# Charting

# Line Graph

```{r}
chartSeries(msft,
            type = "candlestick",
            subset = "2007-05-10::2007-10-10",
            theme = chartTheme("black"))
```

# Bollinger Bands

```{r}
msft <- getSymbols("MSFT", auto.assign = F)
chartSeries(msft,
            subset = "2007",
            TA = c(addBBands(n = 20, sd = 2), addRSI()),
            theme = chartTheme("black"))
```

# EMA

```{r}
msft <- getSymbols("MSFT", auto.assign = F)
chartSeries(msft,
            subset = "2007",
            TA = c(addBBands(n = 20, sd = 2), addRSI(),
            addEMA(n = 30), addMACD()),
            theme = chartTheme("black"))
```

# Others

Next Project : we'll use technical indicators to create buy and sell signals.